providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "22.14"

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "pnpm install --frozen-lockfile --ignore-scripts",
  "pnpm rebuild"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"